version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 767397873937.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-golang-helloworld-app .
      - docker tag my-golang-helloworld-app:latest 767397873937.dkr.ecr.us-east-2.amazonaws.com/my-golang-helloworld-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 767397873937.dkr.ecr.us-east-2.amazonaws.com/helloworld:latest
      - echo Build completed on `date`

artifacts:
  files:
    - Dockerfile
    - main.go

cache:
  paths:
    - "/root/.cache/go-build/**/*"
